### ISSUE TITLE
Any concerns about calcardbackup moving to codeberg.org?

### ISSUE THREAD

**Issue by BernieO** [Cyconet/docker-calcardbackup#3]
I am thinking about moving https://github.com/BernieO/calcardbackup to https://codeberg.org which is based on https://gitea.com

Would calcardbackup moving to Codeberg have any negative effects for your docker-calcardbackup?

**Comment by waja** [comment]
Hi @BernieO,

it's just that I'm subscribed to your repo releases to get notified and need to adjust the download [part](https://github.com/Cyconet/docker-calcardbackup/blob/development/Dockerfile#L33) of my `Dockerfile`.

**Comment by BernieO** [comment]
That seems to be possible to adjust with reasonable effort ;-)

I am still not sure whether I will do the move. But if I do so, I will let you know.

**Comment by BernieO** [comment]
I am planning to move calcardbackup to codeberg.org on January 17th 2020.

The URL of the repo will then be:  
[https://codeberg.org/BernieO/calcardbackup](https://codeberg.org/BernieO/calcardbackup)

Very convenient: just replace `github.com` with `codeberg.org` and you are done 🙂

**Comment by BernieO** [comment]
The migration was successful. See you at codeberg.org

**Comment by waja** [comment]
Hi @BernieO,

> Very convenient: just replace github.com with codeberg.org and you are done

any idea how to substitute `curl -L $(curl -s https://api.github.com/repos/$GIT_PROJECT/releases/latest | jq -r ".tarball_url") | tar xz --strip=1` (https://github.com/Cyconet/docker-calcardbackup/blob/development/Dockerfile#L33)?

**Comment by BernieO** [comment]
Haha, not as convenient as I thought it would be :-)

According to [the api documentation of gitea](https://try.gitea.io/api/swagger#/repository/repoListReleases) and [the manual of `jq`](https://stedolan.github.io/jq/manual/)
replacing
```

$(curl -s https://api.github.com/repos/$GIT_PROJECT/releases/latest | jq -r ".tarball_url")
```
with
```
$(curl -s https://codeberg.org/api/v1/repos/$GIT_PROJECT/releases | jq -r ".[0].tarball_url")
```
should do the trick.

**Comment by waja** [comment]
@BernieO thanks for pointing out. I was searching a bit and found https://docs.gitea.io/en-us/api-usage/, but was too lame to find the link to https://try.gitea.io/api/swagger. :(
